import { PartyColoursDE, PartyColoursTransDE } from "$lib/partyColours";

export const name = 'Bundestagswahl 2025';
export const date = ['2025-02-23'];

export const data = {
  labels: ['SPD', 'CDU/CSU', 'Grüne', 'FDP', 'AfD', 'Linke', 'BSW'],
  datasets: [
    {
      label: 'SPD (2021)',
      data: [25.74, 0, 0, 0, 0, 0, 0],
      backgroundColor: PartyColoursTransDE.SPD,
      index: 0,
      order: 2,
      stack: 'previous',
      categoryPercentage: 0.6,
      barPercentage: 1.3,
    },
    {
      label: 'CDU (2021)',
      data: [0, 18.90, 0, 0, 0, 0, 0],
      backgroundColor: PartyColoursTransDE.CDU,
      index: 1,
      order: 2,
      stack: 'previous',
      categoryPercentage: 0.6,
      barPercentage: 1.3,
    },
    {
      label: 'CSU (2021)',
      data: [0, 5.17, 0, 0, 0, 0, 0],
      backgroundColor: PartyColoursTransDE.CSU,
      index: 1,
      order: 2,
      stack: 'previous',
      categoryPercentage: 0.6,
      barPercentage: 1.3,
    },
    {
      label: 'Grüne (2021)',
      data: [0, 0, 14.75, 0, 0, 0, 0],
      backgroundColor: PartyColoursTransDE.GRUENE,
      index: 2,
      order: 2,
      stack: 'previous',
      categoryPercentage: 0.6,
      barPercentage: 1.3,
    },
    {
      label: 'FDP (2021)',
      data: [0, 0, 0, 11.46, 0, 0, 0],
      backgroundColor: PartyColoursTransDE.FDP,
      index: 3,
      order: 2,
      stack: 'previous',
      categoryPercentage: 0.6,
      barPercentage: 1.3,
    },
    {
      label: 'AfD (2021)',
      data: [0, 0, 0, 0, 10.34, 0, 0],
      backgroundColor: PartyColoursTransDE.AFD,
      index: 4,
      order: 2,
      stack: 'previous',
      categoryPercentage: 0.6,
      barPercentage: 1.3,
    },
    {
      label: 'Linke (2021)',
      data: [0, 0, 0, 0, 0, 4.89, 0],
      backgroundColor: PartyColoursTransDE.LINKE,
      index: 5,
      order: 2,
      stack: 'previous',
      categoryPercentage: 0.6,
      barPercentage: 1.3,
    },
    {
      label: 'BSW (2021)',
      data: [0, 0, 0, 0, 0, 0, 0.00],
      backgroundColor: PartyColoursTransDE.BSW,
      index: 6,
      order: 2,
      stack: 'previous',
      categoryPercentage: 0.6,
      barPercentage: 1.3,
    },
    {
      label: 'SPD',
      data: [25.74, 0, 0, 0, 0, 0, 0],
      backgroundColor: PartyColoursDE.SPD,
      index: 0,
      order: 1,
      stack: 'current',
      categoryPercentage: 0.35,
      barPercentage: 3,
    },
    {
      label: 'CDU',
      data: [0, 18.90, 0, 0, 0, 0, 0],
      backgroundColor: PartyColoursDE.CDU,
      index: 1,
      order: 1,
      stack: 'current',
      categoryPercentage: 0.35,
      barPercentage: 3,
    },
    {
      label: 'CSU',
      data: [0, 5.17, 0, 0, 0, 0, 0],
      backgroundColor: PartyColoursDE.CSU,
      index: 1,
      order: 1,
      stack: 'current',
      categoryPercentage: 0.35,
      barPercentage: 3,
    },
    {
      label: 'Grüne',
      data: [0, 0, 14.75, 0, 0, 0, 0],
      backgroundColor: PartyColoursDE.GRUENE,
      index: 2,
      order: 1,
      stack: 'current',
      categoryPercentage: 0.35,
      barPercentage: 3,
    },
    {
      label: 'FDP',
      data: [0, 0, 0, 11.46, 0, 0, 0],
      backgroundColor: PartyColoursDE.FDP,
      index: 3,
      order: 1,
      stack: 'current',
      categoryPercentage: 0.35,
      barPercentage: 3,
    },
    {
      label: 'AfD',
      data: [0, 0, 0, 0, 10.34, 0, 0],
      backgroundColor: PartyColoursDE.AFD,
      index: 4,
      order: 1,
      stack: 'current',
      categoryPercentage: 0.35,
      barPercentage: 3,
    },
    {
      label: 'Linke',
      data: [0, 0, 0, 0, 0, 4.89, 0],
      backgroundColor: PartyColoursDE.LINKE,
      index: 5,
      order: 1,
      stack: 'current',
      categoryPercentage: 0.35,
      barPercentage: 3,
    },
    {
      label: 'BSW',
      data: [0, 0, 0, 0, 0, 0, 0.00],
      backgroundColor: PartyColoursDE.BSW,
      index: 6,
      order: 1,
      stack: 'current',
      categoryPercentage: 0.35,
      barPercentage: 3,
    },
  ],
};

export const mandateData = {
  labels: ['SPD', 'CDU', 'CSU', 'Grüne', 'FDP', 'AfD', 'Linke', 'BSW'],
  datasets: [
    {
      label: 'Mandate (2021)',
      data: [206, 152, 45, 118, 91, 83, 39, 0.00],
      backgroundColor: [
        PartyColoursTransDE.SPD,
        PartyColoursTransDE.CDU,
        PartyColoursTransDE.CSU,
        PartyColoursTransDE.GRUENE,
        PartyColoursTransDE.FDP,
        PartyColoursTransDE.AFD,
        PartyColoursTransDE.LINKE,
        PartyColoursTransDE.BSW,
      ],
      weight: 0.4,
    },
    {
      label: 'Mandate',
      data: [25.74, 18.90, 5.17, 14.75, 11.46, 10.34, 4.89, 0.00],
      backgroundColor: [
        PartyColoursDE.SPD,
        PartyColoursDE.CDU,
        PartyColoursDE.CSU,
        PartyColoursDE.GRUENE,
        PartyColoursDE.FDP,
        PartyColoursDE.AFD,
        PartyColoursDE.LINKE,
        PartyColoursDE.BSW,
      ],
    },
  ],
};

export const majorityData = {
  labels: ['Mandate'],
  datasets: [
    {
      label: 'SPD',
      data: [188],
      backgroundColor: PartyColoursDE.SPD,
    },
    {
      label: 'CDU',
      data: [138],
      backgroundColor: PartyColoursDE.CDU,
      hidden: true,
    },
    {
      label: 'CSU',
      data: [38],
      backgroundColor: PartyColoursDE.CSU,
      hidden: true,
    },
    {
      label: 'Grüne',
      data: [107],
      backgroundColor: PartyColoursDE.GRUENE,
    },
    {
      label: 'FDP',
      data: [84],
      backgroundColor: PartyColoursDE.FDP,
    },
    {
      label: 'AfD',
      data: [75],
      backgroundColor: PartyColoursDE.AFD,
      hidden: true,
    },
    {
      label: 'Linke',
      data: [0],
      backgroundColor: PartyColoursDE.LINKE,
      hidden: true,
    },
    {
      label: 'BSW',
      data: [0],
      backgroundColor: PartyColoursDE.BSW,
      hidden: true,
    },
  ],
};